#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace englishsnsVS10.datacontext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="englishdict")]
	public partial class CustomerInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertcomments(comments instance);
    partial void Updatecomments(comments instance);
    partial void Deletecomments(comments instance);
    partial void Insertshares(shares instance);
    partial void Updateshares(shares instance);
    partial void Deleteshares(shares instance);
    partial void Insertusers(users instance);
    partial void Updateusers(users instance);
    partial void Deleteusers(users instance);
    partial void Insertfollowers(followers instance);
    partial void Updatefollowers(followers instance);
    partial void Deletefollowers(followers instance);
    #endregion
		
		public CustomerInfoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["englishdictConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<comments> comments
		{
			get
			{
				return this.GetTable<comments>();
			}
		}
		
		public System.Data.Linq.Table<shares> shares
		{
			get
			{
				return this.GetTable<shares>();
			}
		}
		
		public System.Data.Linq.Table<users> users
		{
			get
			{
				return this.GetTable<users>();
			}
		}
		
		public System.Data.Linq.Table<followers> followers
		{
			get
			{
				return this.GetTable<followers>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.comments")]
	public partial class comments : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _comment;
		
		private System.DateTime _time;
		
		private int _userid;
		
		private int _shareid;
		
		private EntityRef<shares> _shares;
		
		private EntityRef<users> _users;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OntimeChanging(System.DateTime value);
    partial void OntimeChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnshareidChanging(int value);
    partial void OnshareidChanged();
    #endregion
		
		public comments()
		{
			this._shares = default(EntityRef<shares>);
			this._users = default(EntityRef<users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime NOT NULL")]
		public System.DateTime time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shareid", DbType="Int NOT NULL")]
		public int shareid
		{
			get
			{
				return this._shareid;
			}
			set
			{
				if ((this._shareid != value))
				{
					if (this._shares.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnshareidChanging(value);
					this.SendPropertyChanging();
					this._shareid = value;
					this.SendPropertyChanged("shareid");
					this.OnshareidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="shares_comments", Storage="_shares", ThisKey="shareid", OtherKey="id", IsForeignKey=true)]
		public shares shares
		{
			get
			{
				return this._shares.Entity;
			}
			set
			{
				shares previousValue = this._shares.Entity;
				if (((previousValue != value) 
							|| (this._shares.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._shares.Entity = null;
						previousValue.comments.Remove(this);
					}
					this._shares.Entity = value;
					if ((value != null))
					{
						value.comments.Add(this);
						this._shareid = value.id;
					}
					else
					{
						this._shareid = default(int);
					}
					this.SendPropertyChanged("shares");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_comments", Storage="_users", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public users users
		{
			get
			{
				return this._users.Entity;
			}
			set
			{
				users previousValue = this._users.Entity;
				if (((previousValue != value) 
							|| (this._users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._users.Entity = null;
						previousValue.comments.Remove(this);
					}
					this._users.Entity = value;
					if ((value != null))
					{
						value.comments.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(int);
					}
					this.SendPropertyChanged("users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.shares")]
	public partial class shares : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sharecontent;
		
		private System.DateTime _sharetime;
		
		private int _userid;
		
		private EntitySet<comments> _comments;
		
		private EntityRef<users> _users;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsharecontentChanging(string value);
    partial void OnsharecontentChanged();
    partial void OnsharetimeChanging(System.DateTime value);
    partial void OnsharetimeChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    #endregion
		
		public shares()
		{
			this._comments = new EntitySet<comments>(new Action<comments>(this.attach_comments), new Action<comments>(this.detach_comments));
			this._users = default(EntityRef<users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sharecontent", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string sharecontent
		{
			get
			{
				return this._sharecontent;
			}
			set
			{
				if ((this._sharecontent != value))
				{
					this.OnsharecontentChanging(value);
					this.SendPropertyChanging();
					this._sharecontent = value;
					this.SendPropertyChanged("sharecontent");
					this.OnsharecontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sharetime", DbType="DateTime NOT NULL")]
		public System.DateTime sharetime
		{
			get
			{
				return this._sharetime;
			}
			set
			{
				if ((this._sharetime != value))
				{
					this.OnsharetimeChanging(value);
					this.SendPropertyChanging();
					this._sharetime = value;
					this.SendPropertyChanged("sharetime");
					this.OnsharetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="shares_comments", Storage="_comments", ThisKey="id", OtherKey="shareid")]
		public EntitySet<comments> comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				this._comments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_shares", Storage="_users", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public users users
		{
			get
			{
				return this._users.Entity;
			}
			set
			{
				users previousValue = this._users.Entity;
				if (((previousValue != value) 
							|| (this._users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._users.Entity = null;
						previousValue.shares.Remove(this);
					}
					this._users.Entity = value;
					if ((value != null))
					{
						value.shares.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(int);
					}
					this.SendPropertyChanged("users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_comments(comments entity)
		{
			this.SendPropertyChanging();
			entity.shares = this;
		}
		
		private void detach_comments(comments entity)
		{
			this.SendPropertyChanging();
			entity.shares = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _name;
		
		private EntitySet<comments> _comments;
		
		private EntitySet<shares> _shares;
		
		private EntitySet<followers> _followers;
		
		private EntitySet<followers> _followers1;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public users()
		{
			this._comments = new EntitySet<comments>(new Action<comments>(this.attach_comments), new Action<comments>(this.detach_comments));
			this._shares = new EntitySet<shares>(new Action<shares>(this.attach_shares), new Action<shares>(this.detach_shares));
			this._followers = new EntitySet<followers>(new Action<followers>(this.attach_followers), new Action<followers>(this.detach_followers));
			this._followers1 = new EntitySet<followers>(new Action<followers>(this.attach_followers1), new Action<followers>(this.detach_followers1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_comments", Storage="_comments", ThisKey="id", OtherKey="userid")]
		public EntitySet<comments> comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				this._comments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_shares", Storage="_shares", ThisKey="id", OtherKey="userid")]
		public EntitySet<shares> shares
		{
			get
			{
				return this._shares;
			}
			set
			{
				this._shares.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_followers", Storage="_followers", ThisKey="id", OtherKey="userid")]
		public EntitySet<followers> followers
		{
			get
			{
				return this._followers;
			}
			set
			{
				this._followers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_followers1", Storage="_followers1", ThisKey="id", OtherKey="follower")]
		public EntitySet<followers> followers1
		{
			get
			{
				return this._followers1;
			}
			set
			{
				this._followers1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_comments(comments entity)
		{
			this.SendPropertyChanging();
			entity.users = this;
		}
		
		private void detach_comments(comments entity)
		{
			this.SendPropertyChanging();
			entity.users = null;
		}
		
		private void attach_shares(shares entity)
		{
			this.SendPropertyChanging();
			entity.users = this;
		}
		
		private void detach_shares(shares entity)
		{
			this.SendPropertyChanging();
			entity.users = null;
		}
		
		private void attach_followers(followers entity)
		{
			this.SendPropertyChanging();
			entity.users = this;
		}
		
		private void detach_followers(followers entity)
		{
			this.SendPropertyChanging();
			entity.users = null;
		}
		
		private void attach_followers1(followers entity)
		{
			this.SendPropertyChanging();
			entity.users1 = this;
		}
		
		private void detach_followers1(followers entity)
		{
			this.SendPropertyChanging();
			entity.users1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.followers")]
	public partial class followers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _userid;
		
		private System.Nullable<int> _follower;
		
		private EntityRef<users> _users;
		
		private EntityRef<users> _users1;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnfollowerChanging(System.Nullable<int> value);
    partial void OnfollowerChanged();
    #endregion
		
		public followers()
		{
			this._users = default(EntityRef<users>);
			this._users1 = default(EntityRef<users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_follower", DbType="Int")]
		public System.Nullable<int> follower
		{
			get
			{
				return this._follower;
			}
			set
			{
				if ((this._follower != value))
				{
					if (this._users1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfollowerChanging(value);
					this.SendPropertyChanging();
					this._follower = value;
					this.SendPropertyChanged("follower");
					this.OnfollowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_followers", Storage="_users", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public users users
		{
			get
			{
				return this._users.Entity;
			}
			set
			{
				users previousValue = this._users.Entity;
				if (((previousValue != value) 
							|| (this._users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._users.Entity = null;
						previousValue.followers.Remove(this);
					}
					this._users.Entity = value;
					if ((value != null))
					{
						value.followers.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(int);
					}
					this.SendPropertyChanged("users");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_followers1", Storage="_users1", ThisKey="follower", OtherKey="id", IsForeignKey=true)]
		public users users1
		{
			get
			{
				return this._users1.Entity;
			}
			set
			{
				users previousValue = this._users1.Entity;
				if (((previousValue != value) 
							|| (this._users1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._users1.Entity = null;
						previousValue.followers1.Remove(this);
					}
					this._users1.Entity = value;
					if ((value != null))
					{
						value.followers1.Add(this);
						this._follower = value.id;
					}
					else
					{
						this._follower = default(Nullable<int>);
					}
					this.SendPropertyChanged("users1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
