<?xml version="1.0" encoding="utf-8"?><Database Name="englishdict" Class="englishdictDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\englishdict.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="englishdictConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.words" Member="words">
    <Type Name="word">
      <Column Name="wordname" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="word_explanation" Member="explanations" ThisKey="wordname" OtherKey="wordname" Type="explanation" />
    </Type>
  </Table>
  <Table Name="dbo.explanations" Member="explanations">
    <Type Name="explanation">
      <Column Name="wordname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="expcontent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="word_explanation" Member="word" ThisKey="wordname" OtherKey="wordname" Type="word" IsForeignKey="true" />
    </Type>
  </Table>
</Database>